import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import {
  MessageSquare,
  Sparkles,
  TrendingUp,
  Users,
  ArrowRight,
  Zap,
  Shield,
  Database,
  Activity,
  Lock,
  ChevronRight
} from 'lucide-react';
import { useAuthStore } from '../store/useAuthStore';

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5, delay, ease: 'easeOut' }
});

const DashboardHome = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const firstName = user?.email?.split('@')[0] || 'User';
  const isSuperAdmin = user?.role === 'SUPER_ADMIN';
  const isDeptAdmin = user?.role === 'DEPARTMENT_ADMIN';

  const stats = [
    {
      label: 'Total Queries',
      value: '0',
      sub: 'All time',
      icon: MessageSquare,
      color: '#818cf8',
      bg: 'rgba(129,140,248,0.1)',
      border: 'rgba(129,140,248,0.2)',
    },
    {
      label: 'AI Engine',
      value: 'Online',
      sub: 'Mistral · Local',
      icon: Zap,
      color: '#34d399',
      bg: 'rgba(52,211,153,0.1)',
      border: 'rgba(52,211,153,0.2)',
    },
    {
      label: 'Team Members',
      value: '1',
      sub: 'In your department',
      icon: Users,
      color: '#f472b6',
      bg: 'rgba(244,114,182,0.1)',
      border: 'rgba(244,114,182,0.2)',
    },
    {
      label: 'Data Security',
      value: '100%',
      sub: 'On-premise · Private',
      icon: Shield,
      color: '#fb923c',
      bg: 'rgba(251,146,60,0.1)',
      border: 'rgba(251,146,60,0.2)',
    },
  ];

  const quickActions = [
    {
      title: 'Enterprise Search',
      description: 'Query your departmental knowledge base with AI-powered retrieval.',
      icon: MessageSquare,
      gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
      glow: 'rgba(99,102,241,0.3)',
      action: () => navigate('/chat'),
      badge: 'RAG',
    },
    {
      title: 'Document Vault',
      description: 'Upload, manage, and embed documents securely for AI retrieval.',
      icon: Database,
      gradient: 'linear-gradient(135deg, #0ea5e9, #06b6d4)',
      glow: 'rgba(14,165,233,0.3)',
      action: () => navigate('/admin'),
      badge: 'Secure',
    },
    {
      title: 'Analytics',
      description: 'Monitor team activity, AI usage patterns, and productivity metrics.',
      icon: TrendingUp,
      gradient: 'linear-gradient(135deg, #f59e0b, #f97316)',
      glow: 'rgba(245,158,11,0.3)',
      action: () => {},
      badge: 'Soon',
    },
  ];

  const highlights = [
    { icon: Lock, title: 'Zero Data Leakage', desc: 'All queries processed locally. Nothing leaves your network.' },
    { icon: Activity, title: 'Real-time Streaming', desc: 'AI answers stream live as they are generated by the engine.' },
    { icon: Shield, title: 'Role-based Isolation', desc: 'Department data is strictly isolated. No cross-dept access.' },
  ];

  return (
    <div style={{ minHeight: '100vh', padding: 'clamp(20px, 2vw, 32px) clamp(16px, 2vw, 32px)', fontFamily: "'Inter', sans-serif" }}>
      <div style={{ maxWidth: '950px', marginLeft: '0' }}>

      {/* ── Header Row ── */}
      <motion.div {...fadeUp(0)} style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 'clamp(24px, 2vw, 36px)', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <p style={{ fontSize: '10px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(148,163,184,0.6)', marginBottom: '8px' }}>
            Good {new Date().getHours() < 12 ? 'Morning' : new Date().getHours() < 18 ? 'Afternoon' : 'Evening'}
          </p>
          <h1 style={{ fontSize: 'clamp(20px, 2vw, 32px)', fontWeight: 900, color: '#f1f5f9', lineHeight: 1.1, margin: 0 }}>
            Welcome back,{' '}
            <span style={{ background: 'linear-gradient(90deg,#818cf8,#a78bfa,#ec4899)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              {firstName}
            </span>
          </h1>
          <p style={{ marginTop: '10px', fontSize: 'clamp(10px, 1vw, 14px)', color: 'rgba(148,163,184,0.75)', margin: '10px 0 0' }}>
            Your AI-powered enterprise workspace is active and ready.
          </p>
        </div>

        {/* Role Badge */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: 'clamp(8px, 1vw, 14px) clamp(12px, 1.6vw, 22px)',
          borderRadius: '100px', background: isSuperAdmin ? 'rgba(220,38,38,0.1)' : isDeptAdmin ? 'rgba(251,146,60,0.1)' : 'rgba(129,140,248,0.1)',
          border: `1px solid ${isSuperAdmin ? 'rgba(220,38,38,0.25)' : isDeptAdmin ? 'rgba(251,146,60,0.25)' : 'rgba(129,140,248,0.25)'}`,
          color: isSuperAdmin ? '#f87171' : isDeptAdmin ? '#fb923c' : '#818cf8',
          fontSize: 'clamp(10px, 0.8vw, 12px)', fontWeight: 700, whiteSpace: 'nowrap', alignSelf: 'flex-start'
        }}>
          {isSuperAdmin ? '👑' : isDeptAdmin ? '🛡️' : '👤'}
          {isSuperAdmin ? 'Super Admin' : isDeptAdmin ? 'Department Admin' : 'Employee'}
        </div>
      </motion.div>

      {/* ── KPI Stats Row ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 'clamp(10px, 1.2vw, 18px)', marginBottom: 'clamp(24px, 2.5vw, 40px)' }}>
        {stats.map((s, i) => {
          const Icon = s.icon;
          return (
            <motion.div key={s.label} {...fadeUp(0.05 + i * 0.07)}
              style={{ padding: 'clamp(16px, 2vw, 28px)', borderRadius: 'clamp(12px, 1.2vw, 20px)',
                background: 'rgba(255,255,255,0.03)', border: `1px solid ${s.border}`,
                position: 'relative', overflow: 'hidden', cursor: 'default' }}>
              {/* Glow orb */}
              <div style={{ position: 'absolute', top: '-20px', right: '-20px', width: '80px', height: '80px',
                borderRadius: '50%', background: `radial-gradient(circle, ${s.bg} 0%, transparent 70%)` }} />
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'clamp(10px, 1vw, 14px)' }}>
                <div style={{ width: 'clamp(24px, 2.5vw, 36px)', height: 'clamp(24px, 2.5vw, 36px)', borderRadius: 'clamp(6px, 0.6vw, 10px)',
                  background: s.bg, border: `1px solid ${s.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Icon style={{ width: '52%', height: '52%', color: s.color }} />
                </div>
              </div>
              <div style={{ fontSize: 'clamp(20px, 2.5vw, 32px)', fontWeight: 900, color: '#f1f5f9', lineHeight: 1, marginBottom: '6px' }}>{s.value}</div>
              <div style={{ fontSize: 'clamp(10px, 1vw, 12px)', fontWeight: 600, color: '#94a3b8' }}>{s.label}</div>
              <div style={{ fontSize: 'clamp(8px, 0.8vw, 10px)', color: 'rgba(148,163,184,0.45)', marginTop: '3px' }}>{s.sub}</div>
            </motion.div>
          );
        })}
      </div>

      {/* ── Two-column layout: Quick Actions + Security Highlights ── */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 380px', gap: 'clamp(16px, 2vw, 28px)', marginBottom: 'clamp(26px, 3.2vw, 44px)', alignItems: 'start' }}>

        {/* Quick Actions */}
        <div>
          <motion.p {...fadeUp(0.3)} style={{ fontSize: 'clamp(8px, 0.8vw, 12px)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(148,163,184,0.5)', marginBottom: 'clamp(12px, 1.2vw, 18px)' }}>
            Quick Actions
          </motion.p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'clamp(10px, 1.2vw, 16px)' }}>
            {quickActions.map((a, i) => {
              const Icon = a.icon;
              return (
                <motion.div key={a.title} {...fadeUp(0.35 + i * 0.08)}
                  onClick={a.action}
                  style={{ display: 'flex', alignItems: 'center', gap: 'clamp(12px, 1.6vw, 22px)', padding: 'clamp(14px, 1.8vw, 26px)',
                    borderRadius: 'clamp(12px, 1.2vw, 18px)', background: 'rgba(255,255,255,0.025)', border: '1px solid rgba(255,255,255,0.07)',
                    cursor: a.badge === 'Soon' ? 'default' : 'pointer', transition: 'all 0.2s', opacity: a.badge === 'Soon' ? 0.55 : 1 }}
                  whileHover={a.badge !== 'Soon' ? { y: -3, background: 'rgba(255,255,255,0.045)', borderColor: 'rgba(255,255,255,0.12)', boxShadow: `0 8px 32px ${a.glow}` } : {}}
                >
                  <div style={{ width: 'clamp(36px, 3.6vw, 52px)', height: 'clamp(36px, 3.6vw, 52px)', borderRadius: 'clamp(10px, 1vw, 14px)',
                    background: a.gradient, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                    boxShadow: `0 4px 16px ${a.glow}` }}>
                    <Icon style={{ width: '46%', height: '46%', color: '#fff' }} />
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '5px' }}>
                      <span style={{ fontSize: 'clamp(12px, 1.2vw, 16px)', fontWeight: 700, color: '#f1f5f9' }}>{a.title}</span>
                      <span style={{ fontSize: 'clamp(8px, 0.6vw, 10px)', fontWeight: 700, padding: '2px 8px', borderRadius: '100px',
                        background: 'rgba(255,255,255,0.08)', color: 'rgba(148,163,184,0.8)', letterSpacing: '0.05em' }}>{a.badge}</span>
                    </div>
                    <p style={{ fontSize: 'clamp(10px, 1vw, 12px)', color: 'rgba(148,163,184,0.65)', margin: 0, lineHeight: 1.5 }}>{a.description}</p>
                  </div>
                  {a.badge !== 'Soon' && <ChevronRight style={{ width: 'clamp(12px, 1.2vw, 18px)', height: 'clamp(12px, 1.2vw, 18px)', color: 'rgba(148,163,184,0.3)', flexShrink: 0 }} />}
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Security Highlights Panel */}
        <motion.div {...fadeUp(0.4)} style={{ borderRadius: 'clamp(12px, 1.4vw, 20px)', background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', padding: 'clamp(16px, 2vw, 28px)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: 'clamp(16px, 2vw, 26px)' }}>
            <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#34d399', boxShadow: '0 0 8px rgba(52,211,153,0.8)', animation: 'pulse 2s ease-in-out infinite' }} />
            <span style={{ fontSize: 'clamp(8px, 0.8vw, 12px)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'rgba(148,163,184,0.5)' }}>
              Security Status
            </span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'clamp(12px, 1.6vw, 20px)' }}>
            {highlights.map((h, i) => {
              const Icon = h.icon;
              return (
                <div key={h.title} style={{ display: 'flex', gap: 'clamp(10px, 1.2vw, 14px)', alignItems: 'flex-start' }}>
                  <div style={{ width: 'clamp(26px, 2.4vw, 36px)', height: 'clamp(26px, 2.4vw, 36px)', borderRadius: 'clamp(6px, 0.8vw, 10px)',
                    background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <Icon style={{ width: '48%', height: '48%', color: '#34d399' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: 'clamp(10px, 1vw, 14px)', fontWeight: 700, color: '#e2e8f0', marginBottom: '4px' }}>{h.title}</div>
                    <div style={{ fontSize: 'clamp(8px, 0.8vw, 12px)', color: 'rgba(148,163,184,0.55)', lineHeight: 1.55 }}>{h.desc}</div>
                  </div>
                </div>
              );
            })}
          </div>

          <div style={{ marginTop: 'clamp(20px, 2.4vw, 32px)', padding: 'clamp(12px, 1.2vw, 18px)', borderRadius: 'clamp(8px, 1vw, 14px)',
            background: 'rgba(52,211,153,0.07)', border: '1px solid rgba(52,211,153,0.15)', textAlign: 'center' }}>
            <div style={{ fontSize: 'clamp(16px, 1.5vw, 24px)', fontWeight: 900, color: '#34d399', marginBottom: '4px' }}>100%</div>
            <div style={{ fontSize: 'clamp(8px, 0.8vw, 12px)', color: 'rgba(52,211,153,0.7)', fontWeight: 600 }}>On-Premise & Encrypted</div>
          </div>
        </motion.div>
      </div>

      {/* ── CTA Banner ── */}
      <motion.div {...fadeUp(0.6)}
        style={{ borderRadius: 'clamp(12px, 1.4vw, 22px)', padding: 'clamp(22px, 2.8vw, 44px) clamp(26px, 3.2vw, 52px)',
          background: 'linear-gradient(135deg, rgba(99,102,241,0.18) 0%, rgba(168,85,247,0.18) 50%, rgba(236,72,153,0.12) 100%)',
          border: '1px solid rgba(129,140,248,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px', flexWrap: 'wrap',
          position: 'relative', overflow: 'hidden' }}>
        {/* Background orb */}
        <div style={{ position: 'absolute', right: '-60px', top: '50%', transform: 'translateY(-50%)', width: '300px', height: '300px',
          borderRadius: '50%', background: 'radial-gradient(circle, rgba(139,92,246,0.15) 0%, transparent 70%)', pointerEvents: 'none' }} />

        <div style={{ position: 'relative' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
            <Sparkles style={{ width: 'clamp(12px, 1.2vw, 18px)', height: 'clamp(12px, 1.2vw, 18px)', color: '#a78bfa' }} />
            <span style={{ fontSize: 'clamp(8px, 0.8vw, 12px)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', color: '#a78bfa' }}>
              NEXUS AI
            </span>
          </div>
          <h2 style={{ fontSize: 'clamp(16px, 2.2vw, 36px)', fontWeight: 900, color: '#f1f5f9', margin: '0 0 10px', lineHeight: 1.1 }}>
            Start your first search
          </h2>
          <p style={{ fontSize: 'clamp(10px, 1vw, 14px)', color: 'rgba(148,163,184,0.7)', margin: 0, maxWidth: '480px', lineHeight: 1.6 }}>
            Ask anything about your company's knowledge base. Responses are AI-generated from your department's secure documents.
          </p>
        </div>

        <button onClick={() => navigate('/chat')}
          style={{ display: 'flex', alignItems: 'center', gap: 'clamp(6px, 0.8vw, 12px)', padding: 'clamp(12px, 1.2vw, 18px) clamp(20px, 2.2vw, 34px)',
            borderRadius: 'clamp(8px, 1vw, 14px)', background: 'linear-gradient(135deg,#6366f1,#8b5cf6)', color: '#fff',
            fontWeight: 700, fontSize: 'clamp(10px, 1.2vw, 16px)', border: 'none', cursor: 'pointer', whiteSpace: 'nowrap',
            boxShadow: '0 8px 32px rgba(99,102,241,0.4)', transition: 'all 0.2s', flexShrink: 0, position: 'relative' }}
          onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 12px 40px rgba(99,102,241,0.55)'; }}
          onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 8px 32px rgba(99,102,241,0.4)'; }}
        >
          Launch Search Engine
          <ArrowRight style={{ width: 'clamp(12px, 1.2vw, 16px)', height: 'clamp(12px, 1.2vw, 16px)' }} />
        </button>
      </motion.div>

      <style>{`
        @keyframes pulse { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }
      `}</style>
      </div>
    </div>
  );
};

export default DashboardHome;
